global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  scrape_timeout:      10s
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - /etc/prometheus/rules/*

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'master'

    static_configs:
      - targets: ['KMASTER']

  - job_name: node_metrics
    file_sd_configs:
     - files: [/etc/prometheus/node_metrics.yml]

  - job_name: service_probe
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
     - files: [/etc/prometheus/service_probe.yml]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: localhost:9115
      - source_labels: [__param_target]
        target_label: instance
     
  - job_name: pod_metrics
    file_sd_configs:
     - files: [/etc/prometheus/pod_metrics.yml]

  - job_name: container_readiness
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
     - files: [/etc/prometheus/readiness_probe.yml]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: localhost:9115
      - source_labels: [__param_target]
        target_label: instance

  - job_name: container_liveness
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
     - files: [/etc/prometheus/liveness_probe.yml]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: localhost:9115
      - source_labels: [__param_target]
        target_label: instance
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
