[template]
src = "alertmanager.yml.tmpl"
dest = "/etc/alertmanager/alertmanager.yml"
prefix = "/registry/services/specs/default"
keys = [
    "/"
]

reload_cmd = "kill -HUP `cat /etc/service/alertmanager/supervise/pid`"
