[template]
src = "kubernetes.conf.tmpl"
dest = "/prometheus/prometheus.yml"
keys = [
    "/registry/services/specs/default/",
    "/registry/pods/default",
    "/registry/minions/"
]

check_cmd = "sed -i -e '/^[[:space:]]*$/d' {{.src}} && /prometheus/promtool check-config {{.src}}"
reload_cmd = "kill -HUP `cat /etc/service/prometheus/supervise/pid`"
