[template]
src = "kubernetes.conf.tmpl"
dest = "/prometheus/prometheus.yml"
keys = [
    "/registry/services/specs/default/",
    "/registry/pods/default",
    "/registry/minions/"
]

check_cmd = "/prometheus/promtool check-config /prometheus/prometheus.yml"
reload_cmd = "sed -i -e '/^[[:space:]]*$/d' /prometheus/prometheus.yml && kill -HUP `cat /etc/service/prometheus/supervise/pid`"
